(function(b){function u(a){var e=a.data;a.isDefaultPrevented()||(a.preventDefault(),b(this).ajaxSubmit(e))}function y(a){var e=a.target,g=b(e);if(!g.is("[type=submit],[type=image]")){e=g.closest("[type=submit]");if(0===e.length)return;e=e[0]}var d=this;d.clk=e;"image"==e.type&&(void 0!==a.offsetX?(d.clk_x=a.offsetX,d.clk_y=a.offsetY):"function"==typeof b.fn.offset?(g=g.offset(),d.clk_x=a.pageX-g.left,d.clk_y=a.pageY-g.top):(d.clk_x=a.pageX-e.offsetLeft,d.clk_y=a.pageY-e.offsetTop));setTimeout(function(){d.clk=
d.clk_x=d.clk_y=null},100)}function s(){if(b.fn.ajaxSubmit.debug){var a="[jquery.form] "+Array.prototype.join.call(arguments,"");window.console&&window.console.log?window.console.log(a):window.opera&&window.opera.postError&&window.opera.postError(a)}}var A,B;A=void 0!==b("<input type='file'/>").get(0).files;B=void 0!==window.FormData;var D=!!b.fn.prop;b.fn.attr2=function(a,b){if(!D)return this.attr.apply(this,arguments);var g=this.prop.apply(this,arguments);return g&&g.jquery||"string"===typeof g?
g:this.attr.apply(this,arguments)};b.fn.ajaxSubmit=function(a){function e(a){a=b.param(a).split("&");var d=a.length,g=[],e,c;for(e=0;e<d;e++)a[e]=a[e].replace(/\+/g," "),c=a[e].split("="),g.push([decodeURIComponent(c[0]),decodeURIComponent(c[1])]);return g}function g(d){for(var g=new FormData,c=0;c<d.length;c++)g.append(d[c].name,d[c].value);if(a.extraData)for(d=e(a.extraData),c=0;c<d.length;c++)d[c]&&g.append(d[c][0],d[c][1]);a.data=null;c=b.extend(!0,{},b.ajaxSettings,a,{contentType:!1,processData:!1,
cache:!1,type:m||"POST"});a.uploadProgress&&(c.xhr=function(){var b=jQuery.ajaxSettings.xhr();b.upload&&b.upload.addEventListener("progress",function(b){var c=0,d=b.loaded||b.position,g=b.total;b.lengthComputable&&(c=Math.ceil(100*(d/g)));a.uploadProgress(b,d,g,c)},!1);return b});c.data=null;var h=c.beforeSend;c.beforeSend=function(a,b){b.data=g;h&&h.call(this,a,b)};return b.ajax(c)}function d(c){function d(){function a(){try{var b=(r.contentWindow?r.contentWindow.document:r.contentDocument?r.contentDocument:
r.document).readyState;s("state = "+b);b&&"uninitialized"==b.toLowerCase()&&setTimeout(a,50)}catch(c){s("Server abort: ",c," (",c.name,")"),g(y),u&&clearTimeout(u),u=void 0}}var c=p.attr2("target"),k=p.attr2("action");e.setAttribute("target",q);m||e.setAttribute("method","POST");k!=f.url&&e.setAttribute("action",f.url);f.skipEncodingOverride||m&&!/post/i.test(m)||p.attr({encoding:"multipart/form-data",enctype:"multipart/form-data"});f.timeout&&(u=setTimeout(function(){v=!0;g(z)},f.timeout));var h=
[];try{if(f.extraData)for(var l in f.extraData)f.extraData.hasOwnProperty(l)&&(b.isPlainObject(f.extraData[l])&&f.extraData[l].hasOwnProperty("name")&&f.extraData[l].hasOwnProperty("value")?h.push(b('<input type="hidden" name="'+f.extraData[l].name+'">').val(f.extraData[l].value).appendTo(e)[0]):h.push(b('<input type="hidden" name="'+l+'">').val(f.extraData[l]).appendTo(e)[0]));f.iframeTarget||(w.appendTo("body"),r.attachEvent?r.attachEvent("onload",g):r.addEventListener("load",g,!1));setTimeout(a,
15);try{e.submit()}catch(n){document.createElement("form").submit.apply(e)}}finally{e.setAttribute("action",k),c?e.setAttribute("target",c):p.removeAttr("target"),b(h).remove()}}function g(a){if(!k.aborted&&!F){try{t=r.contentWindow?r.contentWindow.document:r.contentDocument?r.contentDocument:r.document}catch(c){s("cannot access response document: ",c),a=y}if(a===z&&k)k.abort("timeout"),x.reject(k,"timeout");else if(a==y&&k)k.abort("server abort"),x.reject(k,"error","server abort");else if(t&&t.location.href!=
f.iframeSrc||v){r.detachEvent?r.detachEvent("onload",g):r.removeEventListener("load",g,!1);a="success";var d;try{if(v)throw"timeout";var e="xml"==f.dataType||t.XMLDocument||b.isXMLDoc(t);s("isXml="+e);if(!e&&window.opera&&(null===t.body||!t.body.innerHTML)&&--B){s("requeing onLoad callback, DOM not available");setTimeout(g,250);return}var h=t.body?t.body:t.documentElement;k.responseText=h?h.innerHTML:null;k.responseXML=t.XMLDocument?t.XMLDocument:t;e&&(f.dataType="xml");k.getResponseHeader=function(a){return{"content-type":f.dataType}[a]};
h&&(k.status=Number(h.getAttribute("status"))||k.status,k.statusText=h.getAttribute("statusText")||k.statusText);var m=(f.dataType||"").toLowerCase(),p=/(json|script|text)/.test(m);if(p||f.textarea){var n=t.getElementsByTagName("textarea")[0];if(n)k.responseText=n.value,k.status=Number(n.getAttribute("status"))||k.status,k.statusText=n.getAttribute("statusText")||k.statusText;else if(p){var q=t.getElementsByTagName("pre")[0],C=t.getElementsByTagName("body")[0];q?k.responseText=q.textContent?q.textContent:
q.innerText:C&&(k.responseText=C.textContent?C.textContent:C.innerText)}}else"xml"==m&&!k.responseXML&&k.responseText&&(k.responseXML=H(k.responseText));try{A=I(k,m,f)}catch(G){a="parsererror",k.error=d=G||a}}catch(E){s("error caught: ",E),a="error",k.error=d=E||a}k.aborted&&(s("upload aborted"),a=null);k.status&&(a=200<=k.status&&300>k.status||304===k.status?"success":"error");"success"===a?(f.success&&f.success.call(f.context,A,"success",k),x.resolve(k.responseText,"success",k),l&&b.event.trigger("ajaxSuccess",
[k,f])):a&&(void 0===d&&(d=k.statusText),f.error&&f.error.call(f.context,k,a,d),x.reject(k,"error",d),l&&b.event.trigger("ajaxError",[k,f,d]));l&&b.event.trigger("ajaxComplete",[k,f]);l&&!--b.active&&b.event.trigger("ajaxStop");f.complete&&f.complete.call(f.context,k,a);F=!0;f.timeout&&clearTimeout(u);setTimeout(function(){f.iframeTarget||w.remove();k.responseXML=null},100)}}}var e=p[0],h,f,l,q,w,r,k,v,u,x=b.Deferred();if(c)for(h=0;h<n.length;h++)c=b(n[h]),D?c.prop("disabled",!1):c.removeAttr("disabled");
f=b.extend(!0,{},b.ajaxSettings,a);f.context=f.context||f;q="jqFormIO"+(new Date).getTime();f.iframeTarget?(w=b(f.iframeTarget),(h=w.attr2("name"))?q=h:w.attr2("name",q)):(w=b('<iframe name="'+q+'" src="'+f.iframeSrc+'" />'),w.css({position:"absolute",top:"-1000px",left:"-1000px"}));r=w[0];k={aborted:0,responseText:null,responseXML:null,status:0,statusText:"n/a",getAllResponseHeaders:function(){},getResponseHeader:function(){},setRequestHeader:function(){},abort:function(a){var c="timeout"===a?"timeout":
"aborted";s("aborting upload... "+c);this.aborted=1;try{r.contentWindow.document.execCommand&&r.contentWindow.document.execCommand("Stop")}catch(d){}w.attr("src",f.iframeSrc);k.error=c;f.error&&f.error.call(f.context,k,c,a);l&&b.event.trigger("ajaxError",[k,f,c]);f.complete&&f.complete.call(f.context,k,c)}};(l=f.global)&&0===b.active++&&b.event.trigger("ajaxStart");l&&b.event.trigger("ajaxSend",[k,f]);if(f.beforeSend&&!1===f.beforeSend.call(f.context,k,f))return f.global&&b.active--,x.reject(),x;
if(k.aborted)return x.reject(),x;(c=e.clk)&&(h=c.name)&&!c.disabled&&(f.extraData=f.extraData||{},f.extraData[h]=c.value,"image"==c.type&&(f.extraData[h+".x"]=e.clk_x,f.extraData[h+".y"]=e.clk_y));var z=1,y=2;c=b("meta[name=csrf-token]").attr("content");(h=b("meta[name=csrf-param]").attr("content"))&&c&&(f.extraData=f.extraData||{},f.extraData[h]=c);f.forceSync?d():setTimeout(d,10);var A,t,B=50,F,H=b.parseXML||function(a,b){window.ActiveXObject?(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",
b.loadXML(a)):b=(new DOMParser).parseFromString(a,"text/xml");return b&&b.documentElement&&"parsererror"!=b.documentElement.nodeName?b:null},J=b.parseJSON||function(a){return window.eval("("+a+")")},I=function(a,c,d){var f=a.getResponseHeader("content-type")||"",e="xml"===c||!c&&0<=f.indexOf("xml");a=e?a.responseXML:a.responseText;e&&"parsererror"===a.documentElement.nodeName&&b.error&&b.error("parsererror");d&&d.dataFilter&&(a=d.dataFilter(a,c));"string"===typeof a&&("json"===c||!c&&0<=f.indexOf("json")?
a=J(a):("script"===c||!c&&0<=f.indexOf("javascript"))&&b.globalEval(a));return a};return x}if(!this.length)return s("ajaxSubmit: skipping submit process - no element selected"),this;var m,c,p=this;"function"==typeof a&&(a={success:a});m=this.attr2("method");c=this.attr2("action");(c=(c="string"===typeof c?b.trim(c):"")||window.location.href||"")&&(c=(c.match(/^([^#]+)/)||[])[1]);a=b.extend(!0,{url:c,success:b.ajaxSettings.success,type:m||"GET",iframeSrc:/^https/i.test(window.location.href||"")?"javascript:false":
"about:blank"},a);c={};this.trigger("form-pre-serialize",[this,a,c]);if(c.veto)return s("ajaxSubmit: submit vetoed via form-pre-serialize trigger"),this;if(a.beforeSerialize&&!1===a.beforeSerialize(this,a))return s("ajaxSubmit: submit aborted via beforeSerialize callback"),this;var l=a.traditional;void 0===l&&(l=b.ajaxSettings.traditional);var n=[],h,q=this.formToArray(a.semantic,n);a.data&&(a.extraData=a.data,h=b.param(a.data,l));if(a.beforeSubmit&&!1===a.beforeSubmit(q,this,a))return s("ajaxSubmit: submit aborted via beforeSubmit callback"),
this;this.trigger("form-submit-validate",[q,this,a,c]);if(c.veto)return s("ajaxSubmit: submit vetoed via form-submit-validate trigger"),this;c=b.param(q,l);h&&(c=c?c+"&"+h:h);"GET"==a.type.toUpperCase()?(a.url+=(0<=a.url.indexOf("?")?"&":"?")+c,a.data=null):a.data=c;var v=[];a.resetForm&&v.push(function(){p.resetForm()});a.clearForm&&v.push(function(){p.clearForm(a.includeHidden)});if(!a.dataType&&a.target){var u=a.success||function(){};v.push(function(c){var d=a.replaceTarget?"replaceWith":"html";
b(a.target)[d](c).each(u,arguments)})}else a.success&&v.push(a.success);a.success=function(b,c,d){for(var e=a.context||this,g=0,f=v.length;g<f;g++)v[g].apply(e,[b,c,d||p,p])};h=0<b('input[type=file]:enabled[value!=""]',this).length;c="multipart/form-data"==p.attr("enctype")||"multipart/form-data"==p.attr("encoding");l=A&&B;s("fileAPI :"+l);var z;!1!==a.iframe&&(a.iframe||(h||c)&&!l)?a.closeKeepAlive?b.get(a.closeKeepAlive,function(){z=d(q)}):z=d(q):z=(h||c)&&l?g(q):b.ajax(a);p.removeData("jqxhr").data("jqxhr",
z);for(h=0;h<n.length;h++)n[h]=null;this.trigger("form-submit-notify",[this,a]);return this};b.fn.ajaxForm=function(a){a=a||{};a.delegation=a.delegation&&b.isFunction(b.fn.on);if(!a.delegation&&0===this.length){var e=this.selector,g=this.context;if(!b.isReady&&e)return s("DOM not ready, queuing ajaxForm"),b(function(){b(e,g).ajaxForm(a)}),this;s("terminating; zero elements found by selector"+(b.isReady?"":" (DOM not ready)"));return this}return a.delegation?(b(document).off("submit.form-plugin",this.selector,
u).off("click.form-plugin",this.selector,y).on("submit.form-plugin",this.selector,a,u).on("click.form-plugin",this.selector,a,y),this):this.ajaxFormUnbind().bind("submit.form-plugin",a,u).bind("click.form-plugin",a,y)};b.fn.ajaxFormUnbind=function(){return this.unbind("submit.form-plugin click.form-plugin")};b.fn.formToArray=function(a,e){var g=[];if(0===this.length)return g;var d=this[0],m=a?d.getElementsByTagName("*"):d.elements;if(!m)return g;var c,p,l,n,h,q;c=0;for(q=m.length;c<q;c++)if(h=m[c],
(l=h.name)&&!h.disabled)if(a&&d.clk&&"image"==h.type)d.clk==h&&(g.push({name:l,value:b(h).val(),type:h.type}),g.push({name:l+".x",value:d.clk_x},{name:l+".y",value:d.clk_y}));else if((n=b.fieldValue(h,!0))&&n.constructor==Array)for(e&&e.push(h),p=0,h=n.length;p<h;p++)g.push({name:l,value:n[p]});else if(A&&"file"==h.type)if(e&&e.push(h),n=h.files,n.length)for(p=0;p<n.length;p++)g.push({name:l,value:n[p],type:h.type});else g.push({name:l,value:"",type:h.type});else null!==n&&"undefined"!=typeof n&&
(e&&e.push(h),g.push({name:l,value:n,type:h.type,required:h.required}));!a&&d.clk&&(m=b(d.clk),c=m[0],(l=c.name)&&!c.disabled&&"image"==c.type&&(g.push({name:l,value:m.val()}),g.push({name:l+".x",value:d.clk_x},{name:l+".y",value:d.clk_y})));return g};b.fn.formSerialize=function(a){return b.param(this.formToArray(a))};b.fn.fieldSerialize=function(a){var e=[];this.each(function(){var g=this.name;if(g){var d=b.fieldValue(this,a);if(d&&d.constructor==Array)for(var m=0,c=d.length;m<c;m++)e.push({name:g,
value:d[m]});else null!==d&&"undefined"!=typeof d&&e.push({name:this.name,value:d})}});return b.param(e)};b.fn.fieldValue=function(a){for(var e=[],g=0,d=this.length;g<d;g++){var m=b.fieldValue(this[g],a);null===m||"undefined"==typeof m||m.constructor==Array&&!m.length||(m.constructor==Array?b.merge(e,m):e.push(m))}return e};b.fieldValue=function(a,e){var g=a.name,d=a.type,m=a.tagName.toLowerCase();void 0===e&&(e=!0);if(e&&(!g||a.disabled||"reset"==d||"button"==d||("checkbox"==d||"radio"==d)&&!a.checked||
("submit"==d||"image"==d)&&a.form&&a.form.clk!=a||"select"==m&&-1==a.selectedIndex))return null;if("select"==m){var c=a.selectedIndex;if(0>c)return null;for(var g=[],m=a.options,p=(d="select-one"==d)?c+1:m.length,c=d?c:0;c<p;c++){var l=m[c];if(l.selected){var n=l.value;n||(n=l.attributes&&l.attributes.value&&!l.attributes.value.specified?l.text:l.value);if(d)return n;g.push(n)}}return g}return b(a).val()};b.fn.clearForm=function(a){return this.each(function(){b("input,select,textarea",this).clearFields(a)})};
b.fn.clearFields=b.fn.clearInputs=function(a){var e=/^(?:color|date|datetime|email|month|number|password|range|search|tel|text|time|url|week)$/i;return this.each(function(){var g=this.type,d=this.tagName.toLowerCase();e.test(g)||"textarea"==d?this.value="":"checkbox"==g||"radio"==g?this.checked=!1:"select"==d?this.selectedIndex=-1:"file"==g?/MSIE/.test(navigator.userAgent)?b(this).replaceWith(b(this).clone(!0)):b(this).val(""):a&&(!0===a&&/hidden/.test(g)||"string"==typeof a&&b(this).is(a))&&(this.value=
"")})};b.fn.resetForm=function(){return this.each(function(){("function"==typeof this.reset||"object"==typeof this.reset&&!this.reset.nodeType)&&this.reset()})};b.fn.enable=function(a){void 0===a&&(a=!0);return this.each(function(){this.disabled=!a})};b.fn.selected=function(a){void 0===a&&(a=!0);return this.each(function(){var e=this.type;"checkbox"==e||"radio"==e?this.checked=a:"option"==this.tagName.toLowerCase()&&(e=b(this).parent("select"),a&&e[0]&&"select-one"==e[0].type&&e.find("option").selected(!1),
this.selected=a)})};b.fn.ajaxSubmit.debug=!1})(jQuery);